site_name: rfproto Docs
site_url: https://johnnygox17.github.io/rfproto/
site_author: John Gentile
site_description: Docs for rfproto repo

repo_name: JohnnyGOX17/rfproto
repo_url: https://github.com/JohnnyGOX17/rfproto

copyright: Copyright &copy; 2024 John Gentile

theme:
  name: "material"
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - mkdocstrings

nav:
  - Home: index.md
  - Modules:
    - Filtering: filtering.md
    - Impairments: impairments.md
    - Measurements: measurements.md
    - Plotting: plot.md
    - Signal Generation: sig_gen.md
    - Utilities: utils.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

