#!/usr/bin/env bash

# cd to git dir root
git_root="$(git rev-parse --show-toplevel)"
pushd "$git_root" > /dev/null

git-print-TODOs
git add "TODO.md"

echo "Running pre-commit Git hook..."
if ! ./scripts/run-tests.sh; then
  echo "ERROR: commit blocked, tests not passing!"
  exit 1
else
  echo "Pre-commit Git hook done!"
fi

popd > /dev/null

